### ISSUE TITLE
Error - File "<frozen importlib._bootstrap>", line 568, in module_from_spec 

### ISSUE THREAD

**Issue by matwerber1** [awslabs/aws-systems-manager-document-generator#1]
Hi, 

Trying to use this utility on an AWS Cloud9 environment and receiving an error when running main.py. 

Steps taken to install: 
```
git clone...
sudo python3 -m pip install aws-systems-manager-document-generator/
#####
Processing ./aws-systems-manager-document-generator
Installing collected packages: SSMDocumentGenerator
  Found existing installation: SSMDocumentGenerator 1.0
    Uninstalling SSMDocumentGenerator-1.0:
      Successfully uninstalled SSMDocumentGenerator-1.0
  Running setup.py install for SSMDocumentGenerator ... done
Successfully installed SSMDocumentGenerator-1.0
```

After install, procedures used to test: 
```
cd build/lib/ssm_document_generator
python3 main.py -cf --indent 2 \
    ./examples/dmesg/dmesg.sh \
    ./examples/dmesg/dmesg.json

```

This is the error received:
```
Traceback (most recent call last):
  File "main.py", line 80, in <module>
    main()
  File "main.py", line 33, in main
    result = process_documents(input_path)
  File "main.py", line 67, in process_documents
    DocumentManager.load(input_path)]
  File "/usr/local/lib/python3.6/site-packages/SSMDocumentGenerator-1.0-py3.6.egg/ssm_document_generator/document_manager.py", line 14, in load
    return utils.load_module(definition_path).definition
  File "/usr/local/lib/python3.6/site-packages/SSMDocumentGenerator-1.0-py3.6.egg/ssm_document_generator/utils/__init__.py", line 9, in load_module
    definition_module = importlib.util.module_from_spec(spec)
  File "<frozen importlib._bootstrap>", line 568, in module_from_spec
AttributeError: 'NoneType' object has no attribute 'loader'
```

**Comment by Stvad** [comment]
Hey @matwerber1, as discussed privately - the input for the program is a definition file.
So the call here would instead look like `python3 main.py -cf --indent 2 /dmesg/dmesg_definition.py ./examples/dmesg/dmesg.json`.

I'll look into updating the Readme to better reflect this
